version: 1.0.{build}

image: Ubuntu

configuration: Release

platform: x64

nuget:

  account_feed: true

  project_feed: true

build:

  publish_nuget: true

  publish_nuget_symbols: true

  include_nuget_references: true

  publish_core_console: true

  verbosity: minimal

deploy:

- provider: NuGet

  server: source "github"

  api_key:

    secure: pFOBijzWDiDlSAG2HEfnrOFBR7O9rSheUCu1M5OYxsqbE9fvjMYlGftzm/4nSB+Q

  username:

    secure: owERwY+7lws5YG7E7kvfgA==

  artifact: bin/Release/dslgrbd.github.io.1.0.0.nupkg

notifications:

- provider: GitHubPullRequest

  auth_token:

    secure: pFOBijzWDiDlSAG2HEfnrOFBR7O9rSheUCu1M5OYxsqbE9fvjMYlGftzm/4nSB+Q

  on_build_success: true

  on_build_failure: false

  on_build_status_changed: true
