version: 1.0.{build}

image: Ubuntu

configuration: Release

platform: x64

nuget:

  account_feed: true

  project_feed: true

build: off

notifications:

- provider: GitHubPullRequest

  auth_token:

    secure: pFOBijzWDiDlSAG2HEfnrOFBR7O9rSheUCu1M5OYxsqbE9fvjMYlGftzm/4nSB+Q

  on_build_success: true

  on_build_failure: false

  on_build_status_changed: true
